### ISSUE TITLE
Crafting Storage Glitch

### ISSUE THREAD

**Issue by Ultrasucc** [ExterminatorX99/MagicStorage#1]
Downloaded the mod earlier, checked it out, neat concept for people who like to play larger modpacks, however there's a glaring issue:
### Something causes the crafting storage interface to glitch out and be stuck on a random item (possibly one selected last) while also not showing any recipes anymore
Tried:

1. Breaking and replacing EVERY MSE block
2. Removing and reinserting stations
3. Unloading and reloading the mod

Nothing worked, hopefully something will be resolved soonTM

**Comment by RectangularObject** [comment]
Only way I could fix this is restarting the game.

**Comment by ExterminatorX99** [comment]
I am unable to reproduce this locally. Could you provide more information and your mod list?

**Comment by Ultrasucc** [comment]
[homealone.zip](https://github.com/ExterminatorX99/MagicStorage/files/6379724/homealone.zip)
Here's the modpack, I don't know what causes it to misbehave like this. I'll try on my next world.

**Comment by Ultrasucc** [comment]
Looking through your code, it seems that you might not be updating the contents of the crafting storage properly and a remnant of some previous item stored in memory (or config or wherever you keep them when not in use). Going through the entire CraftingGUI.cs would be a nightmare as I'm not familiar with what's written in the code and going through line by line comparing changes to try to figure out what causes this is next to impossible (1835 lines of changed code, i.e the entire file, yikes). Assuming that you were the one who made the changes on 2018 with the commit ID 567a607bf46ea5f332b51a7cb1e0b40f16df90ca on a different account, maybe you can figure out what's going on with this thing, as from the newest issue there's another person that's got a similar issue to mine.

**Comment by ExterminatorX99** [comment]
I'm having trouble reproducing this locally. Could you please cause the bug and send me your log file?

**Comment by Ultrasucc** [comment]
I'm also now unable to do this glitch, I'm not sure what caused it in the first place, so I'll close the issue for now. If it happens again, I'll open it back up and post log.
