### ISSUE TITLE
Nested crafting to skip crafting steps

### ISSUE THREAD

**Issue by Jacklz** [ExterminatorX99/MagicStorage#10]
I had an idea for speeding up crafting a little bit and maybe making it a little less tedious by letting the user skip crafting steps while still costing the same amount of ingredients. 

An example would be lets say you wanted to craft a PDA. You currently have everything you need in the storage system EXCEPT for the GPS. And for the GPS you have the compass and the depth meter, but you still need the watch. And so if you have the ingredients required to make the watch, you should be able to craft the GPS. Because the system will see you have the required ingredients and it will auto craft the watch for you when you select to craft the GPS.

You could also make a recipe ingredient appear as a different color if you didn't currently have it the storage system BUT had the ingredients to craft it. And then you could just double click on that item in the ingredients section and the system would craft it for you and place it inside.

Another example, it would allow you to craft turtle armor if you had the required amount of chlorophyte bars and turtle shells in the system, without having to craft the chlorophyte armor. It essentially just saves crafting steps. You could even have it work all the way down to the chlorophyte ore. If you had enough ore, you wouldn't need to craft the bars, to then craft the armor, and then combine with the turtle shells to make turtle armor.

Anyway, just an idea. Could be terrible or hard to implement so feel free to close this anytime.

**Comment by Battikhah** [comment]
To be honest, this is an amazing idea, i dont think there is anyone here that would hate this idea, but the issue is when you have multiple ways to craft something that will be used to craft something else, how would you be able to choose?

**Comment by Jacklz** [comment]
That's a good point, I didn't actually think of that. For items that have one recipe, that'd be simple; but multiple is a different thing. I guess you could have another UI come up with all the recipes that are used to make the item you need, and you could choose it that way. But writing another UI to come up sounds like a lot of work and could be too tedious itself to add in. Not sure, but i'll be brainstorming.

**Comment by ExterminatorX99** [comment]
The [RecursiveCraft](https://github.com/Ishigh1/RecursiveCraft) mod came out the other day and I'm working on using it to allow nested crafting

**Comment by Jacklz** [comment]
oh awesome
