### ISSUE TITLE
Issue with RecursiveCraft - recipes dissapear

### ISSUE THREAD

**Issue by Estions** [ExterminatorX99/MagicStorage#14]
When using RecursiveCraft upon first opening of the crafting terminal all recipes show up, but after a certain number of crafts (the number seems random, but for me normally occurred after 2-3 crafts) all recipes disappear. This issue is solved by closing the terminal and opening it again or sometimes (very unreliably) by removing a random crafting station from it's slot and placing it back in.
At first the recursion threshold for RecursiveCraft was at -1 (so, infinite as I understand), yet after setting it to 0 (the same as vanilla I presume) the issue was still there and only by uninstalling RecursiveCraft was the issue fixed.
The MagicStorage author redirected me here, I am not extremely fluent in how mods exactly work in tModloader, yet it would be nice for the issue to be fixed, especially when it comes to playing with mods like Fargo's Soul Mod.
Thank you for your attention.

**Comment by Jacklz** [comment]
i am also having this same issue
