### ISSUE TITLE
Players not being able to see much items on the interface

### ISSUE THREAD

**Issue by AlvaroluffyBR** [ExterminatorX99/MagicStorage#15]
I and my friend have been having this issue recently, we currently have 1289 items in our system, i could craft normally, while him could not, and now this bug is happening to me, for instance, i tried crafting a solar armor piece, however it doesnt show on the interface, even though i have all the items required to do so, this bug is very annoying, please fix it. Edit: i fixed it by downloading that item checklist and updating the mod

**Comment by KitsuneNoNatsu** [comment]
I have pretty much the same issue
Also some items just disappear once I craft them once, having to then take the crafting table or whatever out, place it down and manually craft things
I've had 1 other person report the same issues
