### ISSUE TITLE
Craftable items not visible in the crafting unit

### ISSUE THREAD

**Issue by KitsuneNoNatsu** [ExterminatorX99/MagicStorage#16]
Clearly able to craft chains, but it doesn't show up no matter what I do
Mod list: 
[enabled.txt](https://github.com/ExterminatorX99/MagicStorage/files/6510630/enabled.txt)
I can't seem to find a log from today

![image](https://user-images.githubusercontent.com/84426602/118856182-59476100-b8df-11eb-8ef6-8dd173a7d8db.png)

**Comment by KitsuneNoNatsu** [comment]
> I am unable to reproduce this locally

I'll try to reinstall the whole thing

**Comment by KitsuneNoNatsu** [comment]
> > I am unable to reproduce this locally
> 
> I'll try to reinstall the whole thing

Reinstalled, still nothing
I deleted everything in TML under Documents and in Steam, still the issue persists

**Comment by ExterminatorX99** [comment]
Does the recipe show up if you remove the Item Checklist mod?

**Comment by KitsuneNoNatsu** [comment]
> > > I am unable to reproduce this locally
> > 
> > 
> > I'll try to reinstall the whole thing
> 
> Reinstalled, still nothing
> I deleted everything in TML under Documents and in Steam, still the issue persists

Also I did reinstall with mods directly from the mod browser, without getting your item checklist version

**Comment by KitsuneNoNatsu** [comment]
> Does the recipe show up if you remove the Item Checklist mod?

Official Item Checklist: Broken recipes
No Item Checklist: I...don't actually see it either

**Comment by ExterminatorX99** [comment]
Have you "found" the anvil?

**Comment by KitsuneNoNatsu** [comment]
> Have you "found" the anvil?

Yes, as I can craft lead armor and other things which require it

**Comment by KitsuneNoNatsu** [comment]
> > Does the recipe show up if you remove the Item Checklist mod?
> 
> Official Item Checklist: Broken recipes
> No Item Checklist: I see it

With your version of item checklist: Broken again

**Comment by KitsuneNoNatsu** [comment]
God now it's gotten worse
![image](https://user-images.githubusercontent.com/84426602/118872409-38880700-b8f1-11eb-836e-7fb42ea37337.png)

**Comment by ExterminatorX99** [comment]
I don't know what's happening.
I just created a new character and a new world, gave myself iron and wood, crafted a work bench and an anvil, and chains show up.

**Comment by ExterminatorX99** [comment]
Do the chains show up for a new character?

**Comment by KitsuneNoNatsu** [comment]
> Do the chains show up for a new character?

Specifically not the chains
![image](https://user-images.githubusercontent.com/84426602/118873750-c9131700-b8f2-11eb-90cd-b05396b83771.png)

**Comment by KitsuneNoNatsu** [comment]
> I don't know what's happening.
> I just created a new character and a new world, gave myself iron and wood, crafted a work bench and an anvil, and chains show up.

Try giving yourself lead instead
My world is lead and I think that maybe the internal processing in item checklist for lead doesn't allow for chains because chains are from "iron"

**Comment by KitsuneNoNatsu** [comment]
Figured it out
Lead does not discovery the recipe for chains
Iron does
https://www.youtube.com/watch?v=H6Hm11UB6Ko

**Comment by ExterminatorX99** [comment]
Should be fixed now

**Comment by KitsuneNoNatsu** [comment]
> Should be fixed now. Try the update

Yep, works now, nice work
