### ISSUE TITLE
Locator and remote storage access  does not work for multiplayer

### ISSUE THREAD

**Issue by MrDirt1223** [ExterminatorX99/MagicStorage#21]
I dont know why this happens. 
When I set it up it only works in Single player. 
Edit 2 -when I host and play the storage system says its not connected to a storage heart when I retry this in single player this does not happen
Edit 3 - I have tried to link it with a new locator item and it tells me "This Access already has a locator, please mine then replace to reset it" After doing this it says "Success" This does not fix anything however and I end up at "This access is not connected to a Storage heart!"
![Magic storage bug](https://user-images.githubusercontent.com/84977628/119996567-e011d300-bf9c-11eb-8fb9-15d0f8750801.png)

**Comment by MrDirt1223** [comment]
Magic Storage - Extra by blushiemagic and wvlad and exterminator 
Banner Checklist by R
Block Swap by Tyfyter
Leveled Thorium compatibility patch By Webmilio, Gotest
Leveled Mod By Gotest, Webmilio
Boss Checklist By SheepishShepherd, jopojelly
Thorium Mod By DivermanSam & the Goons
Webmilios Commons Library By Webmilio
Wingslot By abluescrab

These are all the mods enabled for this world
I also set up the locator and storage access on solo then started Host and Play, The system DOES work on single player but when    I switch to multiplayer it does not work.

**Comment by MrDirt1223** [comment]
After some testing this bug a little more it seems to only work after restarting the world(leaving and rejoining) This is Might be caused by the locator forgetting the Storage heart cords after restarting the world

**Comment by MrDirt1223** [comment]
[New folder.zip](https://github.com/ExterminatorX99/MagicStorage/files/6563788/New.folder.zip)

**Comment by ExterminatorX99** [comment]
You only sent your vanilla(no mods) world file
You only sent your player's minimap data

**Comment by MrDirt1223** [comment]
How would I send the correct files to you? If you want them

**Comment by ExterminatorX99** [comment]
The world is 2 different files - `.wld` `.twld` extensions
The player is 2 different files - `.plr` `.tplr` extensions

**Comment by MrDirt1223** [comment]
[Hell.zip](https://github.com/ExterminatorX99/MagicStorage/files/6566691/Hell.zip)
This should be my world then^
[Soup.zip](https://github.com/ExterminatorX99/MagicStorage/files/6566692/Soup.zip)
This should be my character

**Comment by ExterminatorX99** [comment]
Where is your magic storage system?
More specifically, your storage heart?

**Comment by MrDirt1223** [comment]
3875' West and 264' surface 
You might need to dig to get to it

**Comment by ExterminatorX99** [comment]
Seems to be an issue with the Storage Heart not being loaded when a server is started.
Going near it to load it and going back, without even doing anything, the remote access works.

**Comment by ExterminatorX99** [comment]
Try the new version

**Comment by MrDirt1223** [comment]
Thank you for the help. I wish you luck with the mod
