### ISSUE TITLE
Recipes that can be crafted through recursive craft don't appear until the crafting interface is opened twice

### ISSUE THREAD

**Issue by Jacklz** [ExterminatorX99/MagicStorage#22]
Hey, not sure why this happens. But upon a fresh reload of tmodloader, I enter my world and when i open the crafting interface, the recipes that i can craft through recursive craft show up as red and not craftable. When i close and reopen the crafting interface they then show up as craftable

**Comment by ExterminatorX99** [comment]
Update RecursiveCraft
