### ISSUE TITLE
Magic Storage and Recipe Browser issue

### ISSUE THREAD

**Issue by kubson3824** [ExterminatorX99/MagicStorage#27]
This time, when I open Recipe Browser while using a Crafting Interface or when I open Recipe Browser after using a Crafting Interface, the game doesn't react and I can find this in the logs, not sure if it's a Recipe Browser or a Magic Storage issue or maybe even a RecursiveCraft issue

`[01:22:09] [1/ERROR] [Terraria]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RecipeBrowser.RecipeCatalogueUI.SetRecipe(Int32 index) in RecipeBrowser\RecipeCatalogueUI.cs:line 747
   at RecipeBrowser.UIElements.UIRecipeSlot.Click(UIMouseEvent evt) in RecipeBrowser\UIElements\UIRecipeSlot.cs:line 67
   at Terraria.UI.UserInterface.Update(GameTime time)
   at Terraria.ModLoader.ModHooks.UpdateUI(GameTime gameTime)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main , GameTime )`

Using mods:
`[
  "AlchemistNPC",
  "AutoTrash",
  "Azercadmium",
  "CalamityMod",
  "CalValEX",
  "ElementsAwoken",
  "Fargowiltas",
  "FargowiltasSouls",
  "Luiafk",
  "MagicStorageExtra",
  "MaxStackExtra",
  "Polarities",
  "RecipeBrowser",
  "Redemption",
  "SacredTools",
  "SpiritMod",
  "Split",
  "StarsAbove",
  "SubworldLibrary",
  "VeinMiner",
  "WingSlot",
  "FKBossHealthBar",
  "BossChecklist",
  "imkSushisMod",
  "imkSushisModAddOn",
  "WMITF",
  "Laugicality",
  "WebmilioCommons",
  "SOTS",
  "FargowiltasSoulsDLC",
  "RecursiveCraft"
]`

Update:
After disabling RecursiveCraft, everything works fine, so I guess it's related to those 3 mods working together?

**Comment by ExterminatorX99** [comment]
This is an issue between RecursiveCraft and RecipeBrowser.
