### ISSUE TITLE
incompatible with blushie's magic storage

### ISSUE THREAD

**Issue by ironsonic79** [ExterminatorX99/MagicStorage#29]
this is more just a question before I make a horrible mistake because they are not compatible if i use this one does all my stuff from Blushie's magic storage or do i need to grab a crap ton of chest to transfer over

**Comment by ExterminatorX99** [comment]
It is currently coded such that it doesn't load together with blushie's version.
And even if it did, you still have to craft all the blocks/components and move all the items
