### ISSUE TITLE
Suggestion for QoL improvement with crafting

### ISSUE THREAD

**Issue by Jacklz** [ExterminatorX99/MagicStorage#3]
Hey, great work on updating this mod so far. I assume blushie's original version is now deprecated? Glad to see someone updating it and adding new sorting icons. I've been wanting that for a long time lol.

I have a suggestion for improving clarity with recipes in the crafting grid. In the section where it shows you the ingredients you need for the recipe, make the background of the item slot red if you currently don't have the item with its required amount in the storage system. For mods with larger recipes it can be a hassle to identify which items you still need for the recipe. I think it offers a quick way to easily pinpoint which items you need to get.

I also had an idea for nested crafting. For an example, it would allow you to craft turtle armor if you had the required amount of chlorophyte bars and turtle shells in the system, without having to craft the chlorophyte armor. It essentially just saves crafting steps. You could even have it work all the way down to the chlorophyte ore. If you had enough ore, you wouldn't need to craft the bars, to then craft the armor, and then combine with the turtle shells to make turtle armor. However, this one would probably be a lot harder than the suggestion mentioned above.

Edit: Another idea I had is to make the icons for vanity, armor, and equipment different so you can differentiate which one to click on without having to read it. So for vanity items you use like the winter cape or something. Same goes for ammo and throwing, and sort by value and dps.

**Comment by ExterminatorX99** [comment]
Implemented your first suggestion

**Comment by ExterminatorX99** [comment]
Also, would you mind closing this issue and opening separate ones for each suggestion?
It would help with organization and would allow me to close them as I implement them

**Comment by ExterminatorX99** [comment]
Changed art for icons
