### ISSUE TITLE
Interface refuses to show up

### ISSUE THREAD

**Issue by M1keyOnDiscord** [ExterminatorX99/MagicStorage#32]
Title says it. Unsure of what causes it. Gets this error in-game instead of either the crafting or heart GUI popping up 
![unknown](https://user-images.githubusercontent.com/86483740/123446334-9f9e7880-d58d-11eb-8fc3-7a6281874b67.png)

**Comment by ExterminatorX99** [comment]
Can you send logs?

**Comment by M1keyOnDiscord** [comment]
[client.log](https://github.com/ExterminatorX99/MagicStorage/files/6717826/client.log)

Here's your logs. I replaced extra with normal Magic and it worked fine, and I might lose all my items in magic storage but it wasnt much anyways lol

**Comment by ExterminatorX99** [comment]
I can't reproduce this locally so I need you to test it. Does this fix it?

[MagicStorageExtra.zip](https://github.com/ExterminatorX99/MagicStorage/files/6718121/MagicStorageExtra.zip)

**Comment by M1keyOnDiscord** [comment]
Let me test it and I'll edit this msg with my results

**Comment by ExterminatorX99** [comment]
How about this?
[MagicStorageExtra.zip](https://github.com/ExterminatorX99/MagicStorage/files/6718227/MagicStorageExtra.zip)

**Comment by M1keyOnDiscord** [comment]
Fixed the msgs, but the GUI is invisable still. I'll just send my client log cause nothing is different except the chat in this case
[client.log](https://github.com/ExterminatorX99/MagicStorage/files/6718309/client.log)

**Comment by ExterminatorX99** [comment]
Try breaking and placing the heart

**Comment by M1keyOnDiscord** [comment]
Doesnt change a thing. I should add on that it _is_ acting like the GUI is opened in the sense I cant shift-click items into the trash and puts it into the heart. But GUI isnt there so I cant retrieve them lul. The Crafting one does not to seem have the same property, but prevents me from trashing stuff while opened aswell.

**Comment by ExterminatorX99** [comment]
How does this one do?
[MagicStorageExtra.zip](https://github.com/ExterminatorX99/MagicStorage/files/6718340/MagicStorageExtra.zip)

**Comment by M1keyOnDiscord** [comment]
I see no difference between this one and the last one, but because I had to restart my Terraria you can see a cleaner log
[client.log](https://github.com/ExterminatorX99/MagicStorage/files/6718370/client.log)

**Comment by ExterminatorX99** [comment]
No errors happened this time but based on the previous one, it seems the game is convinced there is no heart placed

Could you try placing the heart somewhere else?
And test if it works without the Krpg mod

**Comment by M1keyOnDiscord** [comment]
Will test that right now

**Comment by ExterminatorX99** [comment]
Since it works without KRPG, then it's out of my hands. Report the issue to KRPG devs
