### ISSUE TITLE
Installed on server and get error on start up

### ISSUE THREAD

**Issue by jasharen** [ExterminatorX99/MagicStorage#33]
Installed and on start up am getting the following error:

Could not load type of field 'MagicStorageExtra.RecursiveCraftIntegration+Members:recipeCache' (0) due to: Could not load file
or assembly 'RecursiveCraft_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by ExterminatorX99** [comment]
Do you have the RecursiveCraft mod installed? If yes, is it the latest version?

**Comment by jasharen** [comment]
That was it :) Thanks
