### ISSUE TITLE
Can't Storage Crafting Interface

### ISSUE THREAD

**Issue by Potatoified** [ExterminatorX99/MagicStorage#4]
I have all the items that the wiki tells me I need for the storage crafting interface, and a normal workbench with nothing near it, and it will not show up in the crafting menu.

**Comment by ExterminatorX99** [comment]
I'm not really sure what wiki you're using.
The recipe is: 1 Storage Component, 1 Diamond, 3 Sapphires
I recommend using the Recipe Browser mod to look up recipes for items
